services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: pg_container
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

  fastapi:
    build:
      context: ./api           # 👈 this points to your FastAPI app folder
      dockerfile: Dockerfile
    image: my-fastapi-app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres       # reference by container name

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
