services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: pg_container
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pg_data:
